### ISSUE TITLE
[UI Design]참손길 디자인 시안 2종 (~12.22)

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/chamsongil#2]
- 메인쪽 사이트빌딩 및 고객 컨펌이 끝나면 그 내용을 바탕으로 메인 디자인 시안 2개  진행
1)  디자인방향 - 방향 A (내용구성 면에서) 약손명가 메인페이지가 우리 홈페이지에 전형적인 내용
2) 디자인방향 - 방향 B 이주민방송, tft, 슬릭처럼 고객층인 2030세대 여성 타깃에 근접, tft 같은 방향으로 전환하는 것도 괜찮을 수 있다. (부장님은 동의한다.)
- https://www.figma.com/file/2qZhdiqU2rA26IHRmH2Xki/Chamsongil-campaignus

**Comment by woonjjang** [comment]
메인 구성 정해서 다음주 21~22일쯤 디자인 시안 전달 / 이번주에는 디자인 시안에 집중해주세요 ~

**Comment by calvin-design** [comment]
1차 전달 시안, 2차 전달 시안 두개로 두가지 버전을 만드는 건가요?

**Comment by woonjjang** [comment]
넵 @calvin-design 화면 구성 확정해서 전달드릴께요.  (디자인방향 A / 디자인방향 B)로 두 가지 버전을 만드는 것에 가깝습니다.

**Comment by woonjjang** [comment]
@calvin-design  https://www.figma.com/file/2qZhdiqU2rA26IHRmH2Xki/Chamsongil-campaignus?node-id=112%3A4

**Comment by woonjjang** [comment]
고생하셨습니다. 

시안 1 : https://www.figma.com/proto/2qZhdiqU2rA26IHRmH2Xki/Chamsongil-campaignus?node-id=12[…]9&viewport=1998%2C1319%2C0.1745365858078003&scaling=scale-down
시안 2 : https://www.figma.com/proto/2qZhdiqU2rA26IHRmH2Xki/Chamsongil-campaignus?node-id=13[…]48&viewport=861%2C1150%2C0.2723065912723541&scaling=scale-down
