### ISSUE TITLE
[UI] 홈 - 시안 개선 1장

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/chamsongil#5]
마지막에 요청했던 navy 색으로 시안2 구성을 확인하고 싶다고 하시더라구요. 
그래서 시안 2 구성을 중심으로 main-color를 navy로 잡고 / Sub-color를 첫 시안 oranage-color로 잡아서 1장만 만들어주세요. 

사진도 추가되었어요. 
메인 슬라이드쪽 사진 괜찮은 것 셀렉해서 넣어주세요.
https://drive.google.com/drive/folders/1tahCiwyvL50TNECDZKwkRd2URf8DDt__

**Comment by calvin-design** [comment]
네, 근데 사진 링크는 404가 뜨네요

**Comment by woonjjang** [comment]
https://drive.google.com/drive/folders/1tahCiwyvL50TNECDZKwkRd2URf8DDt__?usp=sharing

**Comment by calvin-design** [comment]
올려 놓았습니다~ 근데 사진은 음.. 잘모르겠네요

**Comment by woonjjang** [comment]
[메인 페이지 디자인 시안 결정]

어제 보내준 시안 중, 로고 컬러와 오렌지 컬러를 섞어 쓴 것으로 결정했습니다. 
‘홍보동영상’과 ‘고객 이용 후기’ 순서를 바꾸는 것도 내일 볼 수 있을까요. 1안의 ‘네이버 예약’ 컬러 박스를 ‘지점 소개’ 디자인에 적용하는 것은 전화로 여쭤보고 해야 할 것 같습니다. 

>> @calvin-design ‘홍보동영상’과 ‘고객 이용 후기’ 순서를 바꾸는 것 요청왔어요. 위아래 섹션이 바뀌면 어울리게 배경이랑 맞춰 주면 될 듯
>> 최종 시안은 어제 보낸 것으로 최종 결정

**Comment by woonjjang** [comment]
메인 홈 문구수정


배너에 얹힐 카피. 손 잡은 이미지는 안마 시술 사진으로 교체.

<카피>

통증과 스트레스가 사라지는 순간을 경험해보세요

Professional Pain & Stress Healer
참손길지압힐링센터 


2. 참손길 숫자: 집계 중. 사당점과 선릉점만. 

<카피>

느리지만 알차게 성장하는 참손길지압힐링센터

- 누적 방문 고객 > 월평균 방문자 > 재방문율 > 전국 지점 수 순서로 배치
숫자 칸 적절한 곳에 문구 삽입

※ 2017~2019년 사당점과 선릉점의 고객 데이터를 합한 수치임. 


3. 이용 후기

<카피>

“확실히 다르긴 다르네요!”
참손길 고객들의 생생한 이용 후기

- 이용 후기에 고객 사진 노출 안 됨. 남녀 아이콘이나 해당 부위 시술 사진으로 교체 


4. 홍보 동영상 네모 박스 안 내용 교체

<카피>

통증&스트레스 관리는 전문가에게 맡기세요.
정부가 인증한 국가 공인 안마사.
해부, 생리, 병리, 한의학 등 관련 교육 2,000시간 이상 이수
안마사 평균 경력 10년.
참손길이 특별한 이유입니다.


5. 지점 소개 및 예약하기: 우선 그대로. 카피 고민 중

6. 오픈시간/프로그램/예약하기

<오픈시간>

- 일요일 마감시간을 20:00시로 수정
- 문구 삽입. ※ 지점마다 차이가 있으니 확인 후 방문하세요.

<프로그램>

- 문구 삽입. ※ 지점마다 차이가 있으니 확인 후 방문하세요.

7.조합 콘텐츠 / 8.언론보도 / 9.참손길과 함께 해주신 분들: 더 생각해보겠습니다. 

10. 참손길과 함께한 분들 

이 부분을 이번에 새로 만든 ‘참손길과 함께한 분들’로 변경할지, 아니면 기존의 기업 고객과 합칠 것인가 고민되네요.


----------------------------------------------------------

**Comment by woonjjang** [comment]
사진 링크 : https://drive.google.com/drive/folders/1tahCiwyvL50TNECDZKwkRd2URf8DDt__
