### ISSUE TITLE
[세부 UI ]참손길 안마전문성 + 국내 안마사 제도

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/chamsongil#6]
소개
1.1. 참손길 안마전문성(컨펌) https://chamsongil.campaignus.me/expertise
1.2. 국내 안마사 제도(컨펌) https://chamsongil.campaignus.me/domestic-masseur-system

-------------

1.1. 참손길 안마의 전문성

1) 정부가 인증한 공인 안마사 

* 내용 그대로. 사진 교체.
* 아래에 있는 안마사 교육 과목 이동

2) 평균 경력 10년 이상

1), 3)번처럼 새로 만들기. 기존 이미지와 카피는 삭제.  

<카피>

평균 경력 10년 이상

시각장애인 안마사의 안정적인 일자리 창출과 안마에 대한 부정적 인식을 개선하고자 10인의 안마사가 2013년 참손길공동체협동조합을 설립했습니다. (그해 겨울에는 동작구 사당동에 참손길지압힐링센터 1호점을 개설했고 폭발적인 성장에 힘입어 2015년 강남구에 2호점인 선릉점을 개설했습니다.) 조합 설립 취지에 공감한 많은 안마사들이 조합에 가입해 사당점과 선릉점에서 근무했고, 이들은 자신의 경력과 참손길이라는 브랜드를 자산삼아 하나씩 지점을 오픈해 나갔습니다. 참손길 안마사의 대다수가 10년 이상 경력을 가지고 있는 배경입니다.  

3) 지속적인 교육

내용 그대로. 사진 교체(찾아서 줄 것)

4) 높은 재방문율 

“저 안마해주신 선생님 이름이 뭐에요?”
참손길을 첫 방문하시는 분들이 공통으로 묻는 질문입니다. 그리고 다음 방문 때는 지인분과 함께 오십니다. 2018년부터 2020년까지 사당점과 선릉점의 재방문율은 68% ~ 72%입니다. 2020년은 코로나19 상황이라 방문 고객 수는 전보다 많이 줄었지만 재방문율은 70%나 됩니다. 이처럼 참손길 안마의 전문성은 고객님의 높은 재방문율로 입증됩니다.  (엑셀 표 전달)   

5) 기업에서도 찾는 전문 안마사

인터메조, 오더 삭제
메드트로닉스, 로슈, 도시마을발전소, 동작신협 추가 (로고 찾기)

1.2. 국내 안마사 제도

‘안마사제도, 고객 여러분의 건강을 위해 꼭 지켜야 할 제도입니다’ 아래에

“대한안마사협회 홍보동영상 보러 가기” 문구 넣고 링크 
https://youtu.be/kDE1cQWhaGE

-------------------------------------------------------------------------

**Comment by calvin-design** [comment]
1.1 번에 - 아래에 있는 안마사 교육 과목 이동 
이 무슨의미 인가요?

**Comment by woonjjang** [comment]
해부 생리 있는 10개 글박스 영역을 이동해 달라는 요청입니다.
